### ISSUE TITLE
Code License

### ISSUE THREAD

**Issue by mhils** [ethanhs/check_typedpkg#1]
Hi @ethanhs! 

I'd like to adopt some of the logic in this repo for [pdoc](https://pdoc.dev) (https://github.com/mitmproxy/pdoc/issues/239). Assuming this is fine with you, could I ask you to add a LICENSE file here? :)

Thanks!

**Comment by emmatyping** [comment]
Sure thing, consider the code dual licensed CC0 and MIT. I don't have time right now to upload a LICENSE file but I will take a PR or do later.

**Comment by mhils** [comment]
Awesome, thanks a bunch for the speedy reply! 🍰😃

I'm not familiar with the intricacies of dual-licensing, so I'll leave that to you. Your comment is good enough for me. Here's a quick link if you want to go for a single license: https://github.com/ethanhs/check_typedpkg/community/license/new?branch=master
